version: 2
models:
  - name: raw_sales
    description: "Sales data. "
    columns:
      - name: ORDERNUMBER
        data_type: integer
        quote: true
        data_tests:
          - not_null
      - name: QUANTITYORDERED
        data_type: integer
        quote: true
      - name: PRICEEACH
        data_type: double precision
        quote: true
      - name: ORDERLINENUMBER
        data_type: integer
        quote: true
      - name: SALES
        data_type: double precision
        quote: true
      - name: ORDERDATE
        data_type: text
        quote: true
      - name: STATUS
        data_type: text
        quote: true
      - name: QTR_ID
        data_type: integer
        quote: true
      - name: MONTH_ID
        data_type: integer
        quote: true
      - name: YEAR_ID
        data_type: integer
        quote: true
      - name: PRODUCTLINE
        data_type: text
        quote: true
      - name: MSRP
        data_type: integer
        quote: true
      - name: PRODUCTCODE
        data_type: text
        quote: true
      - name: CUSTOMERNAME
        data_type: text
        quote: true
      - name: PHONE
        data_type: text
        quote: true
      - name: ADDRESSLINE1
        data_type: text
        quote: true
      - name: ADDRESSLINE2
        data_type: text
        quote: true
      - name: CITY
        data_type: text
        quote: true
      - name: STATE
        data_type: text
        quote: true
      - name: POSTALCODE
        data_type: text
        quote: true
      - name: COUNTRY
        data_type: text
        quote: true
      - name: TERRITORY
        data_type: text
        quote: true
      - name: CONTACTLASTNAME
        data_type: text
        quote: true
      - name: CONTACTFIRSTNAME
        data_type: text
        quote: true
      - name: DEALSIZE
        data_type: text
        quote: true
