my_project:
  target: DEV
  outputs:
  # ----- Postgres Connections ----- #

    # Development
    DEV:
      type: postgres
      host: localhost
      user: postgres
      password: FpbBCn3okb2ZCLkzsFtemHqg9
      port: 5432
      dbname: db_dbt_dev
      schema: dbt_schema

    # Quality Assurance 
    QA:
      type: postgres
      host: localhost
      user: postgres
      password: FpbBCn3okb2ZCLkzsFtemHqg9
      port: 5432
      dbname: db_dbt_QA
      schema: dbt_schema

   # Production
    PROD:
      type: postgres
      host: localhost
      user: postgres
      password: FpbBCn3okb2ZCLkzsFtemHqg9
      port: 5432
      dbname: db_dbt_PROD
      schema: dbt_schema
