my_project:
  target: DEV
  outputs:
  # ----- Postgres Connections ----- #

    # Development
    DEV:
      type: postgres
      host: localhost
      user: postgres
      password: FpbBCn3okb2ZCLkzsFtemHqg9
      port: 5432
      dbname: db_dbt_dev
      schema: dbt_schema

    # Quality Assurance 
    QA:
      type: postgres
      host: localhost
      user: postgres
      password: FpbBCn3okb2ZCLkzsFtemHqg9
      port: 5432
      dbname: db_dbt_QA
      schema: dbt_schema

   # Production
    PROD:
      type: postgres
      host: localhost
      user: postgres
      password: FpbBCn3okb2ZCLkzsFtemHqg9
      port: 5432
      dbname: db_dbt_PROD
      schema: dbt_schema

  # ----- Databricks Connection ----- # 
    databricks_dev:
      type: databricks
      catalog: default #optional catalog name if you are using Unity Catalog]
      schema: SCHEMA_NAME # Required
      host: YOURORG.databrickshost.com # Required
      http_path: /SQL/YOUR/HTTP/PATH # Required
      token: dapiXXXXXXXXXXXXXXXXXXXXXXX # Required Personal Access Token (PAT) if using token-based authentication
      threads: 1_OR_MORE  # Optional, default 1