my_project:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: FpbBCn3okb2ZCLkzsFtemHqg9
      port: 5432
      dbname: db_dbt
      schema: dbt_schema